[tool.poetry]
name = "Umar's Discord Maths Bot"
version = "0.1.0"
description = "A discord maths bot with functions for quadratic equations, primes, nth powers (e.g. squares, cubes), volume and a calculator."
authors = ["Umar Sharief"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.7.3"
Flask = "^2.0.1"
black-with-tabs = "^19.10b3"
mypy-extensions = "^0.4.3"
discord-variables-plugin = "^1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"